name: CI Pipeline

on:
  push:
    paths:
      - ".github/workflows/ci-pipeline.yml"

jobs:
  Gradle-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
  
  Docker-Image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: sunil0019/my-project
        tags: v1, latest
        registry: docker.io
        dockerfile: .
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
      
