
name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  Gradle build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [11, 17, 18]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
  
  Docker Image build:
    runs-on: ubuntu-latest
    steps:
    uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: sunil0019/my-project:sha-${GITHUB_SHA:0:7}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
  
      
